#!/usr/bin/env bash

alias \
    debug="export XDEBUG_MODE=debug XDEBUG_SESSION=1" \
    update-quick="sudo apt update -y && sudo apt upgrade -y && sudo apt autoremove -y" \
    update="update-quick && omz update && znap pull && brew upgrade && flatpak update -y" \
    sync-backgrounds="rclone sync ~/Pictures/Backgrounds Drive:Backgrounds" \
    gcd="git checkout dev" \
    grbd="git rebase dev" \
    ggc="gcd && ggl && gbda && gfa" \
    gcfi="gc --fixup" \
    grbif="git rebase -i --autosquash" \
    gpb="gl && gcb" \
    lg="lazygit" \
    df='df -x"squashfs"' \
    cm="chezmoi" \
    cms="chezmoi -S ~/.local/share/chezmoi-scripts" \
    cmsl="chezmoi -S ~/.local/share/chezmoi-scripts-local" \
    bye="update-quick && sudo shutdown now" \
    lsa="ls -lah"

if [[ "$OSTYPE" == "linux-gnu"* ]]; then
    ls="ls -hN --color=auto --group-directories-first"
else
    #MAC OS does not supporty -N (Literal e.g. hello\ world instead of 'hello world'
    ls="ls -h --color=auto --group-directories-first"
fi

# Scripts Edit
se() { du -a ~/.dotfiles/* | awk '{print $2}' | grep "$1" | fzf -1 -0 | xargs  -r $EDITOR ;}

# Projects
projects() { [ ! $# -eq 0 ] && cd ~/Projects/$1 &> /dev/null || cd ~/Projects/$(fd --type directory --min-depth 2 --max-depth 2 --base-directory ~/Projects/ | grep "$1" | fzf -1 -0) &> /dev/null ;}
p() { projects $1 }

command -v nvim >/dev/null && alias vim="nvim" vi="nvim" vimdiff="nvim -d" # Use neovim for vim if present.

vf() { fzf | xargs -r -I % $EDITOR % ;}

[ -f ~/.config/.aliasrc_private ] && source ~/.config/.aliasrc_private
