# General rules

windowrule {
    name = full-float
    match:tag = full-float
    float = on
    size = (monitor_w*0.9) (monitor_h*0.9)
}

source = ~/.config/hypr/apps/plexamp.conf
source = ~/.config/hypr/apps/wavebox.conf
source = ~/.config/hypr/apps/bitwarden.conf
source = ~/.config/hypr/apps/todoist.conf
source = ~/.config/hypr/apps/dbeaver.conf
