#!/bin/bash

active_workspace=$(hyprctl activewindow -j | jq -r '.workspace.name')

if [[ "$active_workspace" == special:* ]]; then
    workspace_name="${active_workspace#special:}"
    hyprctl dispatch togglespecialworkspace "$workspace_name"
else
    hyprctl dispatch killactive
fi
